# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='address.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\raddress.proto\x12\tprotobuff\"U\n\tAddressPb\x12\x0f\n\x07houseNo\x18\x01 \x01(\t\x12\x14\n\x0cstreetOrRoad\x18\x02 \x01(\t\x12\x10\n\x08landmark\x18\x03 \x01(\t\x12\x0f\n\x07pincode\x18\x04 \x01(\tb\x06proto3')
)




_ADDRESSPB = _descriptor.Descriptor(
  name='AddressPb',
  full_name='protobuff.AddressPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='houseNo', full_name='protobuff.AddressPb.houseNo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streetOrRoad', full_name='protobuff.AddressPb.streetOrRoad', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark', full_name='protobuff.AddressPb.landmark', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pincode', full_name='protobuff.AddressPb.pincode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['AddressPb'] = _ADDRESSPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressPb = _reflection.GeneratedProtocolMessageType('AddressPb', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSPB,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.AddressPb)
  })
_sym_db.RegisterMessage(AddressPb)


# @@protoc_insertion_point(module_scope)
