# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boolean.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='boolean.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rboolean.proto\x12\tprotobuff\"\x1a\n\tBooleanPb\x12\r\n\x05value\x18\x01 \x01(\x08*/\n\x0b\x42ooleanEnum\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x08\n\x04TRUE\x10\x01\x12\t\n\x05\x46\x41LSE\x10\x02\x62\x06proto3')
)

_BOOLEANENUM = _descriptor.EnumDescriptor(
  name='BooleanEnum',
  full_name='protobuff.BooleanEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRUE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=56,
  serialized_end=103,
)
_sym_db.RegisterEnumDescriptor(_BOOLEANENUM)

BooleanEnum = enum_type_wrapper.EnumTypeWrapper(_BOOLEANENUM)
DEFAULT = 0
TRUE = 1
FALSE = 2



_BOOLEANPB = _descriptor.Descriptor(
  name='BooleanPb',
  full_name='protobuff.BooleanPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuff.BooleanPb.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['BooleanPb'] = _BOOLEANPB
DESCRIPTOR.enum_types_by_name['BooleanEnum'] = _BOOLEANENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BooleanPb = _reflection.GeneratedProtocolMessageType('BooleanPb', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANPB,
  '__module__' : 'boolean_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.BooleanPb)
  })
_sym_db.RegisterMessage(BooleanPb)


# @@protoc_insertion_point(module_scope)
