# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2
import persontypeenum_pb2 as persontypeenum__pb2
import names_pb2 as names__pb2
import summary_pb2 as summary__pb2
import mobile_pb2 as mobile__pb2
import contactdetails_pb2 as contactdetails__pb2
import time_pb2 as time__pb2
import gender_pb2 as gender__pb2
import address_pb2 as address__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63onsumer.proto\x12\tprotobuff\x1a\x0c\x65ntity.proto\x1a\x14persontypeenum.proto\x1a\x0bnames.proto\x1a\rsummary.proto\x1a\x0cmobile.proto\x1a\x14\x63ontactdetails.proto\x1a\ntime.proto\x1a\x0cgender.proto\x1a\raddress.proto\"\x9b\x02\n\nConsumerPb\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12 \n\x04name\x18\x02 \x01(\x0b\x32\x12.protobuff.NamesPb\x12\x33\n\x0e\x63ontactDetails\x18\x03 \x01(\x0b\x32\x1b.protobuff.ContactDetailsPb\x12\x1e\n\x03\x64ob\x18\x04 \x01(\x0b\x32\x11.protobuff.TimePb\x12#\n\x06gender\x18\x05 \x01(\x0b\x32\x13.protobuff.GenderPb\x12%\n\x07\x61\x64\x64ress\x18\x06 \x01(\x0b\x32\x14.protobuff.AddressPb\x12%\n\x04type\x18\x08 \x01(\x0b\x32\x17.protobuff.PersonTypePb\"V\n\rConsumerPbRef\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12 \n\x04name\x18\x02 \x01(\x0b\x32\x12.protobuff.NamesPb\"\x9e\x01\n\x17\x43onsumerSearchRequestPb\x12\'\n\x08lifeTime\x18\x01 \x01(\x0e\x32\x15.protobuff.StatusEnum\x12\x33\n\x0e\x63ontactDetails\x18\x02 \x01(\x0b\x32\x1b.protobuff.ContactDetailsPb\x12%\n\x08mobileNo\x18\x03 \x01(\x0b\x32\x13.protobuff.MobilePb\"i\n\x18\x43onsumerSearchResponsePb\x12%\n\x07summary\x18\x01 \x01(\x0b\x32\x14.protobuff.SummaryPb\x12&\n\x07results\x18\x02 \x03(\x0b\x32\x15.protobuff.ConsumerPbb\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,persontypeenum__pb2.DESCRIPTOR,names__pb2.DESCRIPTOR,summary__pb2.DESCRIPTOR,mobile__pb2.DESCRIPTOR,contactdetails__pb2.DESCRIPTOR,time__pb2.DESCRIPTOR,gender__pb2.DESCRIPTOR,address__pb2.DESCRIPTOR,])




_CONSUMERPB = _descriptor.Descriptor(
  name='ConsumerPb',
  full_name='protobuff.ConsumerPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.ConsumerPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.ConsumerPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contactDetails', full_name='protobuff.ConsumerPb.contactDetails', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dob', full_name='protobuff.ConsumerPb.dob', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='protobuff.ConsumerPb.gender', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='protobuff.ConsumerPb.address', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuff.ConsumerPb.type', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=454,
)


_CONSUMERPBREF = _descriptor.Descriptor(
  name='ConsumerPbRef',
  full_name='protobuff.ConsumerPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.ConsumerPbRef.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.ConsumerPbRef.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=542,
)


_CONSUMERSEARCHREQUESTPB = _descriptor.Descriptor(
  name='ConsumerSearchRequestPb',
  full_name='protobuff.ConsumerSearchRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lifeTime', full_name='protobuff.ConsumerSearchRequestPb.lifeTime', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contactDetails', full_name='protobuff.ConsumerSearchRequestPb.contactDetails', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobileNo', full_name='protobuff.ConsumerSearchRequestPb.mobileNo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=703,
)


_CONSUMERSEARCHRESPONSEPB = _descriptor.Descriptor(
  name='ConsumerSearchResponsePb',
  full_name='protobuff.ConsumerSearchResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='protobuff.ConsumerSearchResponsePb.summary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='protobuff.ConsumerSearchResponsePb.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=705,
  serialized_end=810,
)

_CONSUMERPB.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_CONSUMERPB.fields_by_name['name'].message_type = names__pb2._NAMESPB
_CONSUMERPB.fields_by_name['contactDetails'].message_type = contactdetails__pb2._CONTACTDETAILSPB
_CONSUMERPB.fields_by_name['dob'].message_type = time__pb2._TIMEPB
_CONSUMERPB.fields_by_name['gender'].message_type = gender__pb2._GENDERPB
_CONSUMERPB.fields_by_name['address'].message_type = address__pb2._ADDRESSPB
_CONSUMERPB.fields_by_name['type'].message_type = persontypeenum__pb2._PERSONTYPEPB
_CONSUMERPBREF.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_CONSUMERPBREF.fields_by_name['name'].message_type = names__pb2._NAMESPB
_CONSUMERSEARCHREQUESTPB.fields_by_name['lifeTime'].enum_type = entity__pb2._STATUSENUM
_CONSUMERSEARCHREQUESTPB.fields_by_name['contactDetails'].message_type = contactdetails__pb2._CONTACTDETAILSPB
_CONSUMERSEARCHREQUESTPB.fields_by_name['mobileNo'].message_type = mobile__pb2._MOBILEPB
_CONSUMERSEARCHRESPONSEPB.fields_by_name['summary'].message_type = summary__pb2._SUMMARYPB
_CONSUMERSEARCHRESPONSEPB.fields_by_name['results'].message_type = _CONSUMERPB
DESCRIPTOR.message_types_by_name['ConsumerPb'] = _CONSUMERPB
DESCRIPTOR.message_types_by_name['ConsumerPbRef'] = _CONSUMERPBREF
DESCRIPTOR.message_types_by_name['ConsumerSearchRequestPb'] = _CONSUMERSEARCHREQUESTPB
DESCRIPTOR.message_types_by_name['ConsumerSearchResponsePb'] = _CONSUMERSEARCHRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsumerPb = _reflection.GeneratedProtocolMessageType('ConsumerPb', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERPB,
  '__module__' : 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ConsumerPb)
  })
_sym_db.RegisterMessage(ConsumerPb)

ConsumerPbRef = _reflection.GeneratedProtocolMessageType('ConsumerPbRef', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERPBREF,
  '__module__' : 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ConsumerPbRef)
  })
_sym_db.RegisterMessage(ConsumerPbRef)

ConsumerSearchRequestPb = _reflection.GeneratedProtocolMessageType('ConsumerSearchRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERSEARCHREQUESTPB,
  '__module__' : 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ConsumerSearchRequestPb)
  })
_sym_db.RegisterMessage(ConsumerSearchRequestPb)

ConsumerSearchResponsePb = _reflection.GeneratedProtocolMessageType('ConsumerSearchResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERSEARCHRESPONSEPB,
  '__module__' : 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ConsumerSearchResponsePb)
  })
_sym_db.RegisterMessage(ConsumerSearchResponsePb)


# @@protoc_insertion_point(module_scope)
