# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactdetails.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import email_pb2 as email__pb2
import mobile_pb2 as mobile__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactdetails.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63ontactdetails.proto\x12\tprotobuff\x1a\x0b\x65mail.proto\x1a\x0cmobile.proto\"Z\n\x10\x43ontactDetailsPb\x12!\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x12.protobuff.EmailPb\x12#\n\x06mobile\x18\x02 \x03(\x0b\x32\x13.protobuff.MobilePbb\x06proto3')
  ,
  dependencies=[email__pb2.DESCRIPTOR,mobile__pb2.DESCRIPTOR,])




_CONTACTDETAILSPB = _descriptor.Descriptor(
  name='ContactDetailsPb',
  full_name='protobuff.ContactDetailsPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='protobuff.ContactDetailsPb.email', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile', full_name='protobuff.ContactDetailsPb.mobile', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=152,
)

_CONTACTDETAILSPB.fields_by_name['email'].message_type = email__pb2._EMAILPB
_CONTACTDETAILSPB.fields_by_name['mobile'].message_type = mobile__pb2._MOBILEPB
DESCRIPTOR.message_types_by_name['ContactDetailsPb'] = _CONTACTDETAILSPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContactDetailsPb = _reflection.GeneratedProtocolMessageType('ContactDetailsPb', (_message.Message,), {
  'DESCRIPTOR' : _CONTACTDETAILSPB,
  '__module__' : 'contactdetails_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ContactDetailsPb)
  })
_sym_db.RegisterMessage(ContactDetailsPb)


# @@protoc_insertion_point(module_scope)
