# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deviceinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deviceinfo.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x65viceinfo.proto\x12\tprotobuff\"P\n\x0c\x44\x65viceInfoPb\x12\r\n\x05macId\x18\x01 \x01(\t\x12\x0e\n\x06osType\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x12\n\ndeviceName\x18\x04 \x01(\tb\x06proto3')
)




_DEVICEINFOPB = _descriptor.Descriptor(
  name='DeviceInfoPb',
  full_name='protobuff.DeviceInfoPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='macId', full_name='protobuff.DeviceInfoPb.macId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='osType', full_name='protobuff.DeviceInfoPb.osType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='protobuff.DeviceInfoPb.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceName', full_name='protobuff.DeviceInfoPb.deviceName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['DeviceInfoPb'] = _DEVICEINFOPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceInfoPb = _reflection.GeneratedProtocolMessageType('DeviceInfoPb', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFOPB,
  '__module__' : 'deviceinfo_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.DeviceInfoPb)
  })
_sym_db.RegisterMessage(DeviceInfoPb)


# @@protoc_insertion_point(module_scope)
