# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65mail.proto\x12\tprotobuff\",\n\x07\x45mailPb\x12\x11\n\tlocalpart\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tb\x06proto3')
)




_EMAILPB = _descriptor.Descriptor(
  name='EmailPb',
  full_name='protobuff.EmailPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localpart', full_name='protobuff.EmailPb.localpart', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='protobuff.EmailPb.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['EmailPb'] = _EMAILPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailPb = _reflection.GeneratedProtocolMessageType('EmailPb', (_message.Message,), {
  'DESCRIPTOR' : _EMAILPB,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.EmailPb)
  })
_sym_db.RegisterMessage(EmailPb)


# @@protoc_insertion_point(module_scope)
