# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65mail.proto\x12\tprotobuff\".\n\tEmailIdPb\x12\x11\n\tlocalPart\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"\xd1\x01\n\x0e\x45mailBuilderPb\x12+\n\temailType\x18\x01 \x01(\x0e\x32\x18.protobuff.EmailTypeEnum\x12$\n\x06\x66romId\x18\x02 \x01(\x0b\x32\x14.protobuff.EmailIdPb\x12\"\n\x04toId\x18\x03 \x03(\x0b\x32\x14.protobuff.EmailIdPb\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x0c\n\x04\x66rom\x18\x06 \x01(\t\x12\n\n\x02to\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\x08 \x01(\t*K\n\rEmailTypeEnum\x12\x11\n\rUNKNOWN_EMAIL\x10\x00\x12\x10\n\x0cWELCOME_MAIL\x10\x01\x12\x15\n\x11VERIFICATION_MAIL\x10\x02\x62\x06proto3')
)

_EMAILTYPEENUM = _descriptor.EnumDescriptor(
  name='EmailTypeEnum',
  full_name='protobuff.EmailTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_EMAIL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WELCOME_MAIL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFICATION_MAIL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=286,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_EMAILTYPEENUM)

EmailTypeEnum = enum_type_wrapper.EnumTypeWrapper(_EMAILTYPEENUM)
UNKNOWN_EMAIL = 0
WELCOME_MAIL = 1
VERIFICATION_MAIL = 2



_EMAILIDPB = _descriptor.Descriptor(
  name='EmailIdPb',
  full_name='protobuff.EmailIdPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localPart', full_name='protobuff.EmailIdPb.localPart', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='protobuff.EmailIdPb.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=72,
)


_EMAILBUILDERPB = _descriptor.Descriptor(
  name='EmailBuilderPb',
  full_name='protobuff.EmailBuilderPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emailType', full_name='protobuff.EmailBuilderPb.emailType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromId', full_name='protobuff.EmailBuilderPb.fromId', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toId', full_name='protobuff.EmailBuilderPb.toId', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='protobuff.EmailBuilderPb.subject', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='protobuff.EmailBuilderPb.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from', full_name='protobuff.EmailBuilderPb.from', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='protobuff.EmailBuilderPb.to', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.EmailBuilderPb.name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=284,
)

_EMAILBUILDERPB.fields_by_name['emailType'].enum_type = _EMAILTYPEENUM
_EMAILBUILDERPB.fields_by_name['fromId'].message_type = _EMAILIDPB
_EMAILBUILDERPB.fields_by_name['toId'].message_type = _EMAILIDPB
DESCRIPTOR.message_types_by_name['EmailIdPb'] = _EMAILIDPB
DESCRIPTOR.message_types_by_name['EmailBuilderPb'] = _EMAILBUILDERPB
DESCRIPTOR.enum_types_by_name['EmailTypeEnum'] = _EMAILTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailIdPb = _reflection.GeneratedProtocolMessageType('EmailIdPb', (_message.Message,), {
  'DESCRIPTOR' : _EMAILIDPB,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.EmailIdPb)
  })
_sym_db.RegisterMessage(EmailIdPb)

EmailBuilderPb = _reflection.GeneratedProtocolMessageType('EmailBuilderPb', (_message.Message,), {
  'DESCRIPTOR' : _EMAILBUILDERPB,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.EmailBuilderPb)
  })
_sym_db.RegisterMessage(EmailBuilderPb)


# @@protoc_insertion_point(module_scope)
