# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x65ntity.proto\x12\tprotobuff\"?\n\x08\x45ntityPb\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x08lifeTime\x18\x02 \x01(\x0e\x32\x15.protobuff.StatusEnum*U\n\nStatusEnum\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\r\n\tSUSPUNDED\x10\x03\x12\x0b\n\x07\x42LOCKED\x10\x04\x62\x06proto3')
)

_STATUSENUM = _descriptor.EnumDescriptor(
  name='StatusEnum',
  full_name='protobuff.StatusEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STATUS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUSPUNDED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCKED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=92,
  serialized_end=177,
)
_sym_db.RegisterEnumDescriptor(_STATUSENUM)

StatusEnum = enum_type_wrapper.EnumTypeWrapper(_STATUSENUM)
UNKNOWN_STATUS = 0
ACTIVE = 1
DELETED = 2
SUSPUNDED = 3
BLOCKED = 4



_ENTITYPB = _descriptor.Descriptor(
  name='EntityPb',
  full_name='protobuff.EntityPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuff.EntityPb.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lifeTime', full_name='protobuff.EntityPb.lifeTime', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=90,
)

_ENTITYPB.fields_by_name['lifeTime'].enum_type = _STATUSENUM
DESCRIPTOR.message_types_by_name['EntityPb'] = _ENTITYPB
DESCRIPTOR.enum_types_by_name['StatusEnum'] = _STATUSENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntityPb = _reflection.GeneratedProtocolMessageType('EntityPb', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYPB,
  '__module__' : 'entity_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.EntityPb)
  })
_sym_db.RegisterMessage(EntityPb)


# @@protoc_insertion_point(module_scope)
