# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileconfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileconfig.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66ileconfig.proto\x12\tprotobuff\"a\n\x06\x46ilePb\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x33\n\rextensionEnum\x18\x03 \x01(\x0e\x32\x1c.protobuff.ExtensionTypeEnum\"\x1f\n\x0c\x46ileConfigPb\x12\x0f\n\x07\x66ileUrl\x18\x01 \x01(\t*i\n\x11\x45xtensionTypeEnum\x12\x1a\n\x16UNKNOWN_EXTENSION_TYPE\x10\x00\x12\x0b\n\x07IMG_JPG\x10\x01\x12\x0b\n\x07IMG_PNG\x10\x02\x12\x0b\n\x07IMG_GIF\x10\x03\x12\x08\n\x04TEXT\x10\x04\x12\x07\n\x03PDF\x10\x05\x62\x06proto3')
)

_EXTENSIONTYPEENUM = _descriptor.EnumDescriptor(
  name='ExtensionTypeEnum',
  full_name='protobuff.ExtensionTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_EXTENSION_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMG_JPG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMG_PNG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMG_GIF', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PDF', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_EXTENSIONTYPEENUM)

ExtensionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_EXTENSIONTYPEENUM)
UNKNOWN_EXTENSION_TYPE = 0
IMG_JPG = 1
IMG_PNG = 2
IMG_GIF = 3
TEXT = 4
PDF = 5



_FILEPB = _descriptor.Descriptor(
  name='FilePb',
  full_name='protobuff.FilePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filePath', full_name='protobuff.FilePb.filePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='protobuff.FilePb.fileName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extensionEnum', full_name='protobuff.FilePb.extensionEnum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=128,
)


_FILECONFIGPB = _descriptor.Descriptor(
  name='FileConfigPb',
  full_name='protobuff.FileConfigPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileUrl', full_name='protobuff.FileConfigPb.fileUrl', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=161,
)

_FILEPB.fields_by_name['extensionEnum'].enum_type = _EXTENSIONTYPEENUM
DESCRIPTOR.message_types_by_name['FilePb'] = _FILEPB
DESCRIPTOR.message_types_by_name['FileConfigPb'] = _FILECONFIGPB
DESCRIPTOR.enum_types_by_name['ExtensionTypeEnum'] = _EXTENSIONTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilePb = _reflection.GeneratedProtocolMessageType('FilePb', (_message.Message,), {
  'DESCRIPTOR' : _FILEPB,
  '__module__' : 'fileconfig_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.FilePb)
  })
_sym_db.RegisterMessage(FilePb)

FileConfigPb = _reflection.GeneratedProtocolMessageType('FileConfigPb', (_message.Message,), {
  'DESCRIPTOR' : _FILECONFIGPB,
  '__module__' : 'fileconfig_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.FileConfigPb)
  })
_sym_db.RegisterMessage(FileConfigPb)


# @@protoc_insertion_point(module_scope)
