# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gender.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gender.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cgender.proto\x12\tprotobuff\"1\n\x08GenderPb\x12%\n\x06gender\x18\x01 \x01(\x0e\x32\x15.protobuff.GenderEnum*6\n\nGenderEnum\x12\x12\n\x0eUNKNOWN_GENDER\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x62\x06proto3')
)

_GENDERENUM = _descriptor.EnumDescriptor(
  name='GenderEnum',
  full_name='protobuff.GenderEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_GENDER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=78,
  serialized_end=132,
)
_sym_db.RegisterEnumDescriptor(_GENDERENUM)

GenderEnum = enum_type_wrapper.EnumTypeWrapper(_GENDERENUM)
UNKNOWN_GENDER = 0
MALE = 1
FEMALE = 2



_GENDERPB = _descriptor.Descriptor(
  name='GenderPb',
  full_name='protobuff.GenderPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gender', full_name='protobuff.GenderPb.gender', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=76,
)

_GENDERPB.fields_by_name['gender'].enum_type = _GENDERENUM
DESCRIPTOR.message_types_by_name['GenderPb'] = _GENDERPB
DESCRIPTOR.enum_types_by_name['GenderEnum'] = _GENDERENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenderPb = _reflection.GeneratedProtocolMessageType('GenderPb', (_message.Message,), {
  'DESCRIPTOR' : _GENDERPB,
  '__module__' : 'gender_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.GenderPb)
  })
_sym_db.RegisterMessage(GenderPb)


# @@protoc_insertion_point(module_scope)
