# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genericref.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2
import names_pb2 as names__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='genericref.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10genericref.proto\x12\tprotobuff\x1a\x0c\x65ntity.proto\x1a\x0bnames.proto\"U\n\x0cGenericRefPb\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12 \n\x04name\x18\x02 \x01(\x0b\x32\x12.protobuff.NamesPbb\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,names__pb2.DESCRIPTOR,])




_GENERICREFPB = _descriptor.Descriptor(
  name='GenericRefPb',
  full_name='protobuff.GenericRefPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.GenericRefPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.GenericRefPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=143,
)

_GENERICREFPB.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_GENERICREFPB.fields_by_name['name'].message_type = names__pb2._NAMESPB
DESCRIPTOR.message_types_by_name['GenericRefPb'] = _GENERICREFPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericRefPb = _reflection.GeneratedProtocolMessageType('GenericRefPb', (_message.Message,), {
  'DESCRIPTOR' : _GENERICREFPB,
  '__module__' : 'genericref_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.GenericRefPb)
  })
_sym_db.RegisterMessage(GenericRefPb)


# @@protoc_insertion_point(module_scope)
