# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bimage.proto\x12\tprotobuff\"\x1b\n\x07ImagePb\x12\x10\n\x08imageUrl\x18\x01 \x03(\tb\x06proto3')
)




_IMAGEPB = _descriptor.Descriptor(
  name='ImagePb',
  full_name='protobuff.ImagePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='protobuff.ImagePb.imageUrl', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['ImagePb'] = _IMAGEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImagePb = _reflection.GeneratedProtocolMessageType('ImagePb', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEPB,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.ImagePb)
  })
_sym_db.RegisterMessage(ImagePb)


# @@protoc_insertion_point(module_scope)
