# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobile.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmobile.proto\x12\tprotobuff\"D\n\x08MobilePb\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.protobuff.CountryCodeEnum\x12\x0e\n\x06number\x18\x02 \x01(\t*/\n\x0f\x43ountryCodeEnum\x12\x10\n\x0cUNKNOWN_CODE\x10\x00\x12\n\n\x06ISD_91\x10\x01\x62\x06proto3')
)

_COUNTRYCODEENUM = _descriptor.EnumDescriptor(
  name='CountryCodeEnum',
  full_name='protobuff.CountryCodeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_CODE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISD_91', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=97,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_COUNTRYCODEENUM)

CountryCodeEnum = enum_type_wrapper.EnumTypeWrapper(_COUNTRYCODEENUM)
UNKNOWN_CODE = 0
ISD_91 = 1



_MOBILEPB = _descriptor.Descriptor(
  name='MobilePb',
  full_name='protobuff.MobilePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protobuff.MobilePb.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='protobuff.MobilePb.number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=95,
)

_MOBILEPB.fields_by_name['code'].enum_type = _COUNTRYCODEENUM
DESCRIPTOR.message_types_by_name['MobilePb'] = _MOBILEPB
DESCRIPTOR.enum_types_by_name['CountryCodeEnum'] = _COUNTRYCODEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobilePb = _reflection.GeneratedProtocolMessageType('MobilePb', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEPB,
  '__module__' : 'mobile_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.MobilePb)
  })
_sym_db.RegisterMessage(MobilePb)


# @@protoc_insertion_point(module_scope)
