# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pushnotification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2
import persontypeenum_pb2 as persontypeenum__pb2
import worker_pb2 as worker__pb2
import names_pb2 as names__pb2
import summary_pb2 as summary__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pushnotification.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16pushnotification.proto\x12\tprotobuff\x1a\x0c\x65ntity.proto\x1a\x14persontypeenum.proto\x1a\x0cworker.proto\x1a\x0bnames.proto\x1a\rsummary.proto\"\x9c\x01\n\x12PushNotificationPb\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12)\n\tworkerRef\x18\x02 \x01(\x0b\x32\x16.protobuff.WorkerPbRef\x12%\n\x04type\x18\x03 \x01(\x0b\x32\x17.protobuff.PersonTypePb\x12\x0f\n\x07tokenId\x18\x04 \x01(\t\"\xb4\x01\n\x19PushNotifiactionBuilderPb\x12\x16\n\x0eregistrationId\x18\x01 \x01(\t\x12\x17\n\x0fregistrationIds\x18\x02 \x03(\t\x12\x35\n\x08sendType\x18\x03 \x01(\x0e\x32#.protobuff.SendNotificationTypeEnum\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x10\n\x08imageUrl\x18\x06 \x01(\t\"}\n\x19PushNotificationRequestPb\x12)\n\tworkerRef\x18\x01 \x01(\x0b\x32\x16.protobuff.WorkerPbRef\x12\x35\n\x08sendType\x18\x03 \x01(\x0e\x32#.protobuff.SendNotificationTypeEnum\"s\n\x1fPushNotificationSearchRequestPb\x12)\n\tworkerRef\x18\x01 \x01(\x0b\x32\x16.protobuff.WorkerPbRef\x12%\n\x04type\x18\x02 \x01(\x0b\x32\x17.protobuff.PersonTypePb\"y\n PushNotificationSearchResponsePb\x12%\n\x07summary\x18\x01 \x01(\x0b\x32\x14.protobuff.SummaryPb\x12.\n\x07results\x18\x02 \x03(\x0b\x32\x1d.protobuff.PushNotificationPb*F\n\x18SendNotificationTypeEnum\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x0c\n\x08MULTIPLE\x10\x02\x62\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,persontypeenum__pb2.DESCRIPTOR,worker__pb2.DESCRIPTOR,names__pb2.DESCRIPTOR,summary__pb2.DESCRIPTOR,])

_SENDNOTIFICATIONTYPEENUM = _descriptor.EnumDescriptor(
  name='SendNotificationTypeEnum',
  full_name='protobuff.SendNotificationTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=824,
  serialized_end=894,
)
_sym_db.RegisterEnumDescriptor(_SENDNOTIFICATIONTYPEENUM)

SendNotificationTypeEnum = enum_type_wrapper.EnumTypeWrapper(_SENDNOTIFICATIONTYPEENUM)
UNKNOWN_TYPE = 0
SINGLE = 1
MULTIPLE = 2



_PUSHNOTIFICATIONPB = _descriptor.Descriptor(
  name='PushNotificationPb',
  full_name='protobuff.PushNotificationPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.PushNotificationPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workerRef', full_name='protobuff.PushNotificationPb.workerRef', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuff.PushNotificationPb.type', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tokenId', full_name='protobuff.PushNotificationPb.tokenId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=272,
)


_PUSHNOTIFIACTIONBUILDERPB = _descriptor.Descriptor(
  name='PushNotifiactionBuilderPb',
  full_name='protobuff.PushNotifiactionBuilderPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registrationId', full_name='protobuff.PushNotifiactionBuilderPb.registrationId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registrationIds', full_name='protobuff.PushNotifiactionBuilderPb.registrationIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendType', full_name='protobuff.PushNotifiactionBuilderPb.sendType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='protobuff.PushNotifiactionBuilderPb.subject', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='protobuff.PushNotifiactionBuilderPb.body', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='protobuff.PushNotifiactionBuilderPb.imageUrl', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=455,
)


_PUSHNOTIFICATIONREQUESTPB = _descriptor.Descriptor(
  name='PushNotificationRequestPb',
  full_name='protobuff.PushNotificationRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workerRef', full_name='protobuff.PushNotificationRequestPb.workerRef', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendType', full_name='protobuff.PushNotificationRequestPb.sendType', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=582,
)


_PUSHNOTIFICATIONSEARCHREQUESTPB = _descriptor.Descriptor(
  name='PushNotificationSearchRequestPb',
  full_name='protobuff.PushNotificationSearchRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workerRef', full_name='protobuff.PushNotificationSearchRequestPb.workerRef', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuff.PushNotificationSearchRequestPb.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=699,
)


_PUSHNOTIFICATIONSEARCHRESPONSEPB = _descriptor.Descriptor(
  name='PushNotificationSearchResponsePb',
  full_name='protobuff.PushNotificationSearchResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='summary', full_name='protobuff.PushNotificationSearchResponsePb.summary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='protobuff.PushNotificationSearchResponsePb.results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=822,
)

_PUSHNOTIFICATIONPB.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_PUSHNOTIFICATIONPB.fields_by_name['workerRef'].message_type = worker__pb2._WORKERPBREF
_PUSHNOTIFICATIONPB.fields_by_name['type'].message_type = persontypeenum__pb2._PERSONTYPEPB
_PUSHNOTIFIACTIONBUILDERPB.fields_by_name['sendType'].enum_type = _SENDNOTIFICATIONTYPEENUM
_PUSHNOTIFICATIONREQUESTPB.fields_by_name['workerRef'].message_type = worker__pb2._WORKERPBREF
_PUSHNOTIFICATIONREQUESTPB.fields_by_name['sendType'].enum_type = _SENDNOTIFICATIONTYPEENUM
_PUSHNOTIFICATIONSEARCHREQUESTPB.fields_by_name['workerRef'].message_type = worker__pb2._WORKERPBREF
_PUSHNOTIFICATIONSEARCHREQUESTPB.fields_by_name['type'].message_type = persontypeenum__pb2._PERSONTYPEPB
_PUSHNOTIFICATIONSEARCHRESPONSEPB.fields_by_name['summary'].message_type = summary__pb2._SUMMARYPB
_PUSHNOTIFICATIONSEARCHRESPONSEPB.fields_by_name['results'].message_type = _PUSHNOTIFICATIONPB
DESCRIPTOR.message_types_by_name['PushNotificationPb'] = _PUSHNOTIFICATIONPB
DESCRIPTOR.message_types_by_name['PushNotifiactionBuilderPb'] = _PUSHNOTIFIACTIONBUILDERPB
DESCRIPTOR.message_types_by_name['PushNotificationRequestPb'] = _PUSHNOTIFICATIONREQUESTPB
DESCRIPTOR.message_types_by_name['PushNotificationSearchRequestPb'] = _PUSHNOTIFICATIONSEARCHREQUESTPB
DESCRIPTOR.message_types_by_name['PushNotificationSearchResponsePb'] = _PUSHNOTIFICATIONSEARCHRESPONSEPB
DESCRIPTOR.enum_types_by_name['SendNotificationTypeEnum'] = _SENDNOTIFICATIONTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushNotificationPb = _reflection.GeneratedProtocolMessageType('PushNotificationPb', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFICATIONPB,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.PushNotificationPb)
  })
_sym_db.RegisterMessage(PushNotificationPb)

PushNotifiactionBuilderPb = _reflection.GeneratedProtocolMessageType('PushNotifiactionBuilderPb', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFIACTIONBUILDERPB,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.PushNotifiactionBuilderPb)
  })
_sym_db.RegisterMessage(PushNotifiactionBuilderPb)

PushNotificationRequestPb = _reflection.GeneratedProtocolMessageType('PushNotificationRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFICATIONREQUESTPB,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.PushNotificationRequestPb)
  })
_sym_db.RegisterMessage(PushNotificationRequestPb)

PushNotificationSearchRequestPb = _reflection.GeneratedProtocolMessageType('PushNotificationSearchRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFICATIONSEARCHREQUESTPB,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.PushNotificationSearchRequestPb)
  })
_sym_db.RegisterMessage(PushNotificationSearchRequestPb)

PushNotificationSearchResponsePb = _reflection.GeneratedProtocolMessageType('PushNotificationSearchResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _PUSHNOTIFICATIONSEARCHRESPONSEPB,
  '__module__' : 'pushnotification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.PushNotificationSearchResponsePb)
  })
_sym_db.RegisterMessage(PushNotificationSearchResponsePb)


# @@protoc_insertion_point(module_scope)
