# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import worker_pb2 as worker__pb2
import consumer_pb2 as consumer__pb2
import responsestatusenum_pb2 as responsestatusenum__pb2
import login_pb2 as login__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='registration.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12registration.proto\x12\tprotobuff\x1a\x0cworker.proto\x1a\x0e\x63onsumer.proto\x1a\x18responsestatusenum.proto\x1a\x0blogin.proto\"\x96\x01\n\x15RegistrationRequestPb\x12#\n\x06worker\x18\x01 \x01(\x0b\x32\x13.protobuff.WorkerPb\x12\'\n\x08\x63omsumer\x18\x02 \x01(\x0b\x32\x15.protobuff.ConsumerPb\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x1d\n\x15pushNotificationToken\x18\x04 \x01(\t\"\xb4\x01\n\x16RegistrationResponsePb\x12#\n\x06worker\x18\x01 \x01(\x0b\x32\x13.protobuff.WorkerPb\x12\'\n\x08\x63onsumer\x18\x02 \x01(\x0b\x32\x15.protobuff.ConsumerPb\x12!\n\x05login\x18\x03 \x01(\x0b\x32\x12.protobuff.LoginPb\x12)\n\x06status\x18\x04 \x01(\x0b\x32\x19.protobuff.ResponseTypePbb\x06proto3')
  ,
  dependencies=[worker__pb2.DESCRIPTOR,consumer__pb2.DESCRIPTOR,responsestatusenum__pb2.DESCRIPTOR,login__pb2.DESCRIPTOR,])




_REGISTRATIONREQUESTPB = _descriptor.Descriptor(
  name='RegistrationRequestPb',
  full_name='protobuff.RegistrationRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker', full_name='protobuff.RegistrationRequestPb.worker', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comsumer', full_name='protobuff.RegistrationRequestPb.comsumer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='protobuff.RegistrationRequestPb.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pushNotificationToken', full_name='protobuff.RegistrationRequestPb.pushNotificationToken', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=253,
)


_REGISTRATIONRESPONSEPB = _descriptor.Descriptor(
  name='RegistrationResponsePb',
  full_name='protobuff.RegistrationResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker', full_name='protobuff.RegistrationResponsePb.worker', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer', full_name='protobuff.RegistrationResponsePb.consumer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='protobuff.RegistrationResponsePb.login', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuff.RegistrationResponsePb.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=436,
)

_REGISTRATIONREQUESTPB.fields_by_name['worker'].message_type = worker__pb2._WORKERPB
_REGISTRATIONREQUESTPB.fields_by_name['comsumer'].message_type = consumer__pb2._CONSUMERPB
_REGISTRATIONRESPONSEPB.fields_by_name['worker'].message_type = worker__pb2._WORKERPB
_REGISTRATIONRESPONSEPB.fields_by_name['consumer'].message_type = consumer__pb2._CONSUMERPB
_REGISTRATIONRESPONSEPB.fields_by_name['login'].message_type = login__pb2._LOGINPB
_REGISTRATIONRESPONSEPB.fields_by_name['status'].message_type = responsestatusenum__pb2._RESPONSETYPEPB
DESCRIPTOR.message_types_by_name['RegistrationRequestPb'] = _REGISTRATIONREQUESTPB
DESCRIPTOR.message_types_by_name['RegistrationResponsePb'] = _REGISTRATIONRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegistrationRequestPb = _reflection.GeneratedProtocolMessageType('RegistrationRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUESTPB,
  '__module__' : 'registration_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.RegistrationRequestPb)
  })
_sym_db.RegisterMessage(RegistrationRequestPb)

RegistrationResponsePb = _reflection.GeneratedProtocolMessageType('RegistrationResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONRESPONSEPB,
  '__module__' : 'registration_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.RegistrationResponsePb)
  })
_sym_db.RegisterMessage(RegistrationResponsePb)


# @@protoc_insertion_point(module_scope)
