# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='summary.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rsummary.proto\x12\tprotobuff\"\x1e\n\tSummaryPb\x12\x11\n\ttotalHits\x18\x01 \x01(\x05\x62\x06proto3')
)




_SUMMARYPB = _descriptor.Descriptor(
  name='SummaryPb',
  full_name='protobuff.SummaryPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalHits', full_name='protobuff.SummaryPb.totalHits', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['SummaryPb'] = _SUMMARYPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SummaryPb = _reflection.GeneratedProtocolMessageType('SummaryPb', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYPB,
  '__module__' : 'summary_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.SummaryPb)
  })
_sym_db.RegisterMessage(SummaryPb)


# @@protoc_insertion_point(module_scope)
