# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntask.proto\x12\tprotobuff\x1a\x0c\x65ntity.proto\"-\n\x06TaskPb\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPbb\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,])




_TASKPB = _descriptor.Descriptor(
  name='TaskPb',
  full_name='protobuff.TaskPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.TaskPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=84,
)

_TASKPB.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
DESCRIPTOR.message_types_by_name['TaskPb'] = _TASKPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskPb = _reflection.GeneratedProtocolMessageType('TaskPb', (_message.Message,), {
  'DESCRIPTOR' : _TASKPB,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.TaskPb)
  })
_sym_db.RegisterMessage(TaskPb)


# @@protoc_insertion_point(module_scope)
