# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uid.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tuid.proto\x12\tprotobuff\"\x14\n\x05UIDPb\x12\x0b\n\x03uid\x18\x01 \x01(\tb\x06proto3')
)




_UIDPB = _descriptor.Descriptor(
  name='UIDPb',
  full_name='protobuff.UIDPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='protobuff.UIDPb.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['UIDPb'] = _UIDPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UIDPb = _reflection.GeneratedProtocolMessageType('UIDPb', (_message.Message,), {
  'DESCRIPTOR' : _UIDPB,
  '__module__' : 'uid_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.UIDPb)
  })
_sym_db.RegisterMessage(UIDPb)


# @@protoc_insertion_point(module_scope)
