# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import genericref_pb2 as genericref__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='verification.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12verification.proto\x12\tprotobuff\x1a\x10genericref.proto\"J\n\x0eVerificationPb\x12*\n\tworkerRef\x18\x01 \x01(\x0b\x32\x17.protobuff.GenericRefPb\x12\x0c\n\x04\x63ode\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[genericref__pb2.DESCRIPTOR,])




_VERIFICATIONPB = _descriptor.Descriptor(
  name='VerificationPb',
  full_name='protobuff.VerificationPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workerRef', full_name='protobuff.VerificationPb.workerRef', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='protobuff.VerificationPb.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=125,
)

_VERIFICATIONPB.fields_by_name['workerRef'].message_type = genericref__pb2._GENERICREFPB
DESCRIPTOR.message_types_by_name['VerificationPb'] = _VERIFICATIONPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationPb = _reflection.GeneratedProtocolMessageType('VerificationPb', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONPB,
  '__module__' : 'verification_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.VerificationPb)
  })
_sym_db.RegisterMessage(VerificationPb)


# @@protoc_insertion_point(module_scope)
