# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_pb2 as entity__pb2
import deviceinfo_pb2 as deviceinfo__pb2
import persontypeenum_pb2 as persontypeenum__pb2
import names_pb2 as names__pb2
import genericref_pb2 as genericref__pb2
import contactdetails_pb2 as contactdetails__pb2
import image_pb2 as image__pb2
import time_pb2 as time__pb2
import gender_pb2 as gender__pb2
import address_pb2 as address__pb2
import workertype_pb2 as workertype__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker.proto',
  package='protobuff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cworker.proto\x12\tprotobuff\x1a\x0c\x65ntity.proto\x1a\x10\x64\x65viceinfo.proto\x1a\x14persontypeenum.proto\x1a\x0bnames.proto\x1a\x10genericref.proto\x1a\x14\x63ontactdetails.proto\x1a\x0bimage.proto\x1a\ntime.proto\x1a\x0cgender.proto\x1a\raddress.proto\x1a\x10workertype.proto\"\xda\x03\n\x08WorkerPb\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12 \n\x04name\x18\x02 \x01(\x0b\x32\x12.protobuff.NamesPb\x12\x33\n\x0e\x63ontactDetails\x18\x03 \x01(\x0b\x32\x1b.protobuff.ContactDetailsPb\x12\x1e\n\x03\x64ob\x18\x04 \x01(\x0b\x32\x11.protobuff.TimePb\x12#\n\x06gender\x18\x05 \x01(\x0b\x32\x13.protobuff.GenderPb\x12%\n\x07\x61\x64\x64ress\x18\x06 \x01(\x0b\x32\x14.protobuff.AddressPb\x12\x37\n\x10workerTypeConfig\x18\x07 \x01(\x0b\x32\x1d.protobuff.WorkerTypeConfigPb\x12%\n\x04type\x18\x08 \x01(\x0b\x32\x17.protobuff.PersonTypePb\x12\'\n\x06\x64\x65vice\x18\t \x01(\x0b\x32\x17.protobuff.DeviceInfoPb\x12\'\n\x0bprofilePics\x18\n \x01(\x0b\x32\x12.protobuff.ImagePb\x12\x34\n\x13pushNotificationRef\x18\x0b \x01(\x0b\x32\x17.protobuff.GenericRefPb\"k\n\x12WorkerTypeConfigPb\x12-\n\nworkerType\x18\x01 \x01(\x0e\x32\x19.protobuff.WorkerTypeEnum\x12&\n\ncategories\x18\x02 \x03(\x0b\x32\x12.protobuff.NamesPb\"T\n\x0bWorkerPbRef\x12#\n\x06\x64\x62Info\x18\x01 \x01(\x0b\x32\x13.protobuff.EntityPb\x12 \n\x04name\x18\x02 \x01(\x0b\x32\x12.protobuff.NamesPbb\x06proto3')
  ,
  dependencies=[entity__pb2.DESCRIPTOR,deviceinfo__pb2.DESCRIPTOR,persontypeenum__pb2.DESCRIPTOR,names__pb2.DESCRIPTOR,genericref__pb2.DESCRIPTOR,contactdetails__pb2.DESCRIPTOR,image__pb2.DESCRIPTOR,time__pb2.DESCRIPTOR,gender__pb2.DESCRIPTOR,address__pb2.DESCRIPTOR,workertype__pb2.DESCRIPTOR,])




_WORKERPB = _descriptor.Descriptor(
  name='WorkerPb',
  full_name='protobuff.WorkerPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.WorkerPb.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.WorkerPb.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contactDetails', full_name='protobuff.WorkerPb.contactDetails', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dob', full_name='protobuff.WorkerPb.dob', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='protobuff.WorkerPb.gender', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='protobuff.WorkerPb.address', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workerTypeConfig', full_name='protobuff.WorkerPb.workerTypeConfig', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuff.WorkerPb.type', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='protobuff.WorkerPb.device', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profilePics', full_name='protobuff.WorkerPb.profilePics', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pushNotificationRef', full_name='protobuff.WorkerPb.pushNotificationRef', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=681,
)


_WORKERTYPECONFIGPB = _descriptor.Descriptor(
  name='WorkerTypeConfigPb',
  full_name='protobuff.WorkerTypeConfigPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workerType', full_name='protobuff.WorkerTypeConfigPb.workerType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categories', full_name='protobuff.WorkerTypeConfigPb.categories', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=790,
)


_WORKERPBREF = _descriptor.Descriptor(
  name='WorkerPbRef',
  full_name='protobuff.WorkerPbRef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbInfo', full_name='protobuff.WorkerPbRef.dbInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuff.WorkerPbRef.name', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=792,
  serialized_end=876,
)

_WORKERPB.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_WORKERPB.fields_by_name['name'].message_type = names__pb2._NAMESPB
_WORKERPB.fields_by_name['contactDetails'].message_type = contactdetails__pb2._CONTACTDETAILSPB
_WORKERPB.fields_by_name['dob'].message_type = time__pb2._TIMEPB
_WORKERPB.fields_by_name['gender'].message_type = gender__pb2._GENDERPB
_WORKERPB.fields_by_name['address'].message_type = address__pb2._ADDRESSPB
_WORKERPB.fields_by_name['workerTypeConfig'].message_type = _WORKERTYPECONFIGPB
_WORKERPB.fields_by_name['type'].message_type = persontypeenum__pb2._PERSONTYPEPB
_WORKERPB.fields_by_name['device'].message_type = deviceinfo__pb2._DEVICEINFOPB
_WORKERPB.fields_by_name['profilePics'].message_type = image__pb2._IMAGEPB
_WORKERPB.fields_by_name['pushNotificationRef'].message_type = genericref__pb2._GENERICREFPB
_WORKERTYPECONFIGPB.fields_by_name['workerType'].enum_type = workertype__pb2._WORKERTYPEENUM
_WORKERTYPECONFIGPB.fields_by_name['categories'].message_type = names__pb2._NAMESPB
_WORKERPBREF.fields_by_name['dbInfo'].message_type = entity__pb2._ENTITYPB
_WORKERPBREF.fields_by_name['name'].message_type = names__pb2._NAMESPB
DESCRIPTOR.message_types_by_name['WorkerPb'] = _WORKERPB
DESCRIPTOR.message_types_by_name['WorkerTypeConfigPb'] = _WORKERTYPECONFIGPB
DESCRIPTOR.message_types_by_name['WorkerPbRef'] = _WORKERPBREF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkerPb = _reflection.GeneratedProtocolMessageType('WorkerPb', (_message.Message,), {
  'DESCRIPTOR' : _WORKERPB,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.WorkerPb)
  })
_sym_db.RegisterMessage(WorkerPb)

WorkerTypeConfigPb = _reflection.GeneratedProtocolMessageType('WorkerTypeConfigPb', (_message.Message,), {
  'DESCRIPTOR' : _WORKERTYPECONFIGPB,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.WorkerTypeConfigPb)
  })
_sym_db.RegisterMessage(WorkerTypeConfigPb)

WorkerPbRef = _reflection.GeneratedProtocolMessageType('WorkerPbRef', (_message.Message,), {
  'DESCRIPTOR' : _WORKERPBREF,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:protobuff.WorkerPbRef)
  })
_sym_db.RegisterMessage(WorkerPbRef)


# @@protoc_insertion_point(module_scope)
